# Build plan from the provider
[phases.setup]
nixPkgs = ['nodejs', 'pnpm']
providers = ['...','pnpm']

[phases.install]
cmds=['pnpm install']

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'pnpm start'