export const influencerData = {
	'cultureapothecary': {
		title: 'Welcome to Geviti: Your All-in-One Platform for Personalized Health Optimization',
		description: 'Every body is unique and there is no one-size-fits-all product to heal you. We\'re here to build personalized, longevity-oriented solutions based on the precise needs expressed by your body.',
		image: '/images/cultureapothecary/hero/cultureapothecary.webp',
		solutionImage: '/images/cultureapothecary/hero/cultureapothecary.webp',
		videoUrl: 'https://www.youtube.com/watch?v=kVr1JTxWVQk&t=217s',
		ogImage: '/images/cultureapothecary/hero/og/cultureapothecary.jpeg',
		imageAlt: 'Alex Clark',
		popupReview: '',
		solutionReview: 'Feel like a celebrity with your own personal health concierge service at your fingertips, without the price.',
		thumbnailVideoUrl: '',
		imageTitle: '',
		imageDescription: '',
		accordionData: []
	},
	'wellnessherway': {
		title: 'Welcome to Geviti: Personalized Health Optimization, Designed for Her Journey.',
		description: 'Every body is unique and there is no one-size-fits-all product to heal you. We\'re here to build personalized, longevity-oriented solutions based on the precise needs expressed by your body.',
		image: '/images/cultureapothecary/hero/og/wellnessherway.png',
		ogImage: '/images/cultureapothecary/hero/og/wellnessherway.png',
		imageAlt: 'Gracie Norton',
		popupReview: '',
		videoUrl: '',
		solutionReview: '',
		solutionImage: '',
		thumbnailVideoUrl: '',
		imageTitle: '',
		imageDescription: '',
		accordionData: []
	},
	'deargabby': {
		title: 'Welcome to Geviti, Your Partner in Feeling Younger Every Year.',
		description: 'Every body is unique and there is no one-size-fits-all product to heal you. We\'re here to build personalized, longevity-oriented solutions based on the precise needs expressed by your body.',
		image: '/images/cultureapothecary/hero/deargabby.webp',
		ogImage: '/images/cultureapothecary/hero/og/deargabby.jpeg',
		imageAlt: 'Dear Gabby',
		popupReview: '',
		videoUrl: '',
		solutionReview: '',
		solutionImage: '',
		thumbnailVideoUrl: '',
		imageTitle: '',
		imageDescription: '',
		accordionData: []
	},
	'thatsthepoint': {
		title: 'Welcome to Geviti: Cutting Through the Health Noise with Data-Driven Precision.',
		description: 'Every body is unique and there is no one-size-fits-all product to heal you. We\'re here to build personalized, longevity-oriented solutions based on the precise needs expressed by your body.',
		image: '/images/cultureapothecary/hero/thatsthepoint.webp',
		ogImage: '/images/cultureapothecary/hero/og/thatsthepoint.jpeg',
		imageAlt: 'That’s the Point',
		popupReview: '',
		videoUrl: '',
		solutionReview: '',
		solutionImage: '',
		thumbnailVideoUrl: '',
		imageTitle: '',
		imageDescription: '',
		accordionData: []
	},
	'thebestofyou': {
		title: 'Welcome to Geviti, Your Partner in Feeling Younger Every Year.',
		description: 'Every body is unique and there is no one-size-fits-all product to heal you. We\'re here to build personalized, longevity-oriented solutions based on the precise needs expressed by your body.',
		image: '/images/cultureapothecary/hero/thebestofyou.webp',
		ogImage: '/images/cultureapothecary/hero/og/thebestofyou.png',
		imageAlt: 'The Best of You',
		popupReview: 'Taking charge of your health isn’t just about adding years to your life—it’s about adding life to your years. Geviti makes proactive wellness simple, giving you expert support before issues arise!',
		videoUrl: '',
		solutionReview: '',
		solutionImage: '',
		thumbnailVideoUrl: '',
		imageTitle: '',
		imageDescription: '',
		accordionData: []
	},
	'raisingboysandgirls': {
		title: 'Geviti: Because Your Family Deserves the Healthiest Version of You',
		description: 'Every body is unique and there is no one-size-fits-all product to heal you. We\'re here to build personalized, longevity-oriented solutions based on the precise needs expressed by your body.',
		image: '/images/cultureapothecary/hero/raisingboysandgirls.webp',
		ogImage: '/images/cultureapothecary/hero/og/raisingboysandgirls.jpeg',
		imageAlt: 'Raising boys and girls',
		popupReview: 'Self-care and prioritizing health are important at every age, and we’re grateful to Geviti for making that more accessible to us all!',
		videoUrl: '',
		solutionReview: '',
		solutionImage: '',
		thumbnailVideoUrl: '',
		imageTitle: '',
		imageDescription: '',
		accordionData: []
	},
	'thatsoundsfun': {
		title: 'Welcome to Geviti, Your Partner in Feeling Younger Every Year.',
		description: 'Every body is unique and there is no one-size-fits-all product to heal you. We\'re here to build personalized, longevity-oriented solutions based on the precise needs expressed by your body.',
		image: '/images/cultureapothecary/hero/thatsoundsfun.webp',
		ogImage: '/images/cultureapothecary/hero/og/thatsoundsfun.jpeg',
		imageAlt: 'That sounds fun',
		popupReview: 'Anything we can do to pursue health and prevent illness is worth our time and efforts- Geviti is a perfect tool and teammate to reaching those goals.',
		videoUrl: '',
		solutionReview: '',
		solutionImage: '',
		thumbnailVideoUrl: '',
		imageTitle: '',
		imageDescription: '',
		accordionData: []
	},
	'1000hoursoutside': {
		title: 'Welcome to Geviti, Your Partner in Feeling Younger Every Year.',
		description: 'Every body is unique and there is no one-size-fits-all product to heal you. We\'re here to build personalized, longevity-oriented solutions based on the precise needs expressed by your body.',
		image: '/images/cultureapothecary/hero/1000hoursoutside.jpg',
		ogImage: '/images/cultureapothecary/hero/og/1000hoursoutside.jpeg',
		imageAlt: '1000 Hours Outside',
		popupReview: 'The health of the whole person is something we fully believe in; mind, spirit and body. Geviti has us covered when it comes to understanding the health of our body, and we love that!',
		videoUrl: '',
		solutionReview: '',
		solutionImage: '',
		thumbnailVideoUrl: '',
		imageTitle: '',
		imageDescription: '',
		accordionData: []
	},
	'wellnessandwisdom': {
		title: 'Welcome to Geviti: Advanced Biomarker Analysis for Data-Driven Health Optimization.',
		description: 'Every body is unique and there is no one-size-fits-all product to heal you. We\'re here to build personalized, longevity-oriented solutions based on the precise needs expressed by your body.',
		image: '/images/cultureapothecary/hero/wellnessandwisdom.jpg',
		ogImage: '/images/cultureapothecary/hero/wellnessandwisdom.jpg',
		imageAlt: 'Wellness and Wisdom',
		popupReview: '',
		videoUrl: '',
		solutionReview: '',
		solutionImage: '/images/cultureapothecary/hero/wellnessandwisdom-solution.jpg',
		thumbnailVideoUrl: '',
		imageTitle: '',
		imageDescription: '',
		accordionData: []
	},
	'girlsgonebible': {
		title: 'Welcome to Geviti: Science-Based Health Optimization for Living Your Purpose Fully..',
		description: 'Every body is unique and there is no one-size-fits-all product to heal you. We\'re here to build personalized, longevity-oriented solutions based on the precise needs expressed by your body.',
		image: '/images/cultureapothecary/hero/girlsgonebible.webp',
		ogImage: '/images/cultureapothecary/hero/og/girlsgonebible.jpg',
		imageAlt: 'Girls Gone Bible',
		popupReview: '',
		videoUrl: '',
		solutionReview: '',
		solutionImage: '',
		thumbnailVideoUrl: '',
		imageTitle: '',
		imageDescription: '',
		accordionData: []
	},
	'onward': {
		title: 'Peak Performance Starts With Knowing What Your Body Needs.',
		description: 'Every body is unique and there is no one-size-fits-all product to heal you. We\'re here to build personalized, longevity-oriented solutions based on the precise needs expressed by your body.',
		image: '/images/cultureapothecary/hero/onward.jpg',
		thumbnailVideoUrl: '/images/cultureapothecary/hero/onward.jpg',
		ogImage: '/images/cultureapothecary/hero/onward.jpg',
		imageAlt: 'Wellness and Wisdom',
		popupReview: '',
		videoUrl: 'https://www.youtube.com/watch?v=vLdzl4_27ok',
		solutionReview: '',
		solutionImage: '/images/cultureapothecary/hero/onward-solution.jpg',
		imageTitle: 'DJ Walton',
		imageDescription: 'Boxing Coach & Founder of Onward',
		accordionData: [
			{
				title: 'Chronic Fatigue',
				description:
					'Ongoing sense of exhaustion, low energy, and mental or physical weariness that persists even with adequate rest.',
			},
			{
				title: 'Testosterone Support',
				description:
					'Low testosterone can lead to fatigue, reduced muscle mass, brain fog, and decreased drive—both physically and mentally. Our approach helps restore balance, energy, and performance so you can feel strong, focused, and like yourself again.',
			},
			{
				title: 'Weight Management Issues',
				description:
					'Difficulty achieving or maintaining a healthy weight despite efforts with diet, exercise, or lifestyle changes.',
			},
			{
				title: 'Low Libido',
				description:
					'Persistent lack of sexual desire or interest, often accompanied by reduced arousal or satisfaction, which can stem from hormonal changes, stress, or other health factors.',
			},
			{
				title: 'Cognitive Decline',
				description:
					'Gradual reduction in memory, focus, problem-solving abilities, and overall mental sharpness, often impacting daily functioning and quality of life.',
			},
		]
	},
}