import type { AssessmentQuestion } from './types';

export const assessmentQuestions: AssessmentQuestion[] = [
	{
		id: 'intro',
		kind: 'intro',
	},
	{
		id: 'age',
		kind: 'input',
		title: 'Question 1 - Demographics',
		label: 'What is your current age?',
		context:
      '📊 Age is the #1 factor in biological aging calculations. We\'ll compare your results to healthy individuals in your age group.',
		placeholder: 'Enter your age',
		inputType: 'number',
		min: 18,
		max: 100,
		required: true,
		category: 'Demographics',
	},
	{
		id: 'sex',
		kind: 'options',
		title: 'Question 2 - Demographics',
		label: 'What is your biological sex?',
		context:
      '🧬 Sex affects hormone levels, disease risk, and optimal biomarker ranges. This helps us provide sex-specific recommendations.',
		options: [
			{ value: 'male', label: 'Male', description: 'Testosterone, PSA, and male-specific markers' },
			{ value: 'female', label: 'Female', description: 'Estrogen, progesterone, and female-specific markers' },
		],
		required: true,
		category: 'Demographics',
	},
	{
		id: 'sleep',
		kind: 'options',
		title: 'Question 3 - Sleep Quality',
		label: 'What\'s your average sleep duration AND quality?',
		context:
      '💤 Poor sleep increases cortisol, disrupts growth hormone, and accelerates aging. Quality matters as much as quantity.',
		options: [
			{ value: 'poor-short', label: 'Less than 6 hours + Poor quality', description: 'Frequent waking, not refreshed' },
			{ value: 'poor-adequate', label: '6-8 hours + Poor quality', description: 'Light sleep, wake tired' },
			{ value: 'good-short', label: 'Less than 7 hours + Good quality', description: 'Deep sleep but too short' },
			{ value: 'optimal', label: '7-9 hours + Excellent quality', description: 'Deep, restorative sleep' },
		],
		required: true,
		category: 'Sleep',
	},
	{
		id: 'metabolic',
		kind: 'options',
		title: 'Question 4 - Metabolic Health',
		label: 'Do you experience energy crashes or cravings throughout the day?',
		context:
      '🍎 Blood sugar instability is a key driver of aging. These symptoms indicate poor metabolic flexibility.',
		options: [
			{ value: 'severe', label: 'Severe - Multiple crashes daily', description: 'Need snacks/caffeine to function' },
			{ value: 'moderate', label: 'Moderate - Afternoon slump', description: '3pm energy dip, sugar cravings' },
			{ value: 'mild', label: 'Mild - Occasional dips', description: 'Some days worse than others' },
			{ value: 'stable', label: 'Stable energy all day', description: 'No cravings or crashes' },
		],
		required: true,
		category: 'Metabolic',
	},
	{
		id: 'exercise',
		kind: 'options',
		title: 'Question 5 - Exercise & Movement',
		label: 'What type of exercise do you primarily engage in?',
		context:
      '🏃 Different exercise types affect aging markers differently. We need both cardio (VO2 max) and strength (muscle mass).',
		options: [
			{ value: 'none', label: 'Minimal to no exercise', description: 'Less than 30 min/week' },
			{ value: 'cardio-only', label: 'Cardio only', description: 'Running, cycling, swimming' },
			{ value: 'strength-only', label: 'Strength training only', description: 'Weights, resistance training' },
			{ value: 'combined', label: 'Both cardio + strength', description: 'Balanced exercise program' },
		],
		required: true,
		category: 'Exercise',
	},
	{
		id: 'stress',
		kind: 'options',
		title: 'Question 6 - Stress & Recovery',
		label: 'How well do you recover from stress?',
		context:
      '🧠 Chronic stress ages you faster than smoking. HRV (heart rate variability) is a key longevity marker.',
		options: [
			{ value: 'poor', label: 'Poor - Stress lingers for days', description: 'Anxiety, can\'t \'turn off\'' },
			{ value: 'slow', label: 'Slow - Takes hours to calm down', description: 'Carry tension, poor sleep after stress' },
			{ value: 'moderate', label: 'Moderate - Usually bounce back', description: 'Some resilience, occasional overwhelm' },
			{ value: 'excellent', label: 'Excellent - Quick recovery', description: 'Handle stress well, stay calm' },
		],
		required: true,
		category: 'Stress',
	},
	{
		id: 'fat',
		kind: 'options',
		title: 'Question 7 - Body Composition',
		label: 'Where do you primarily store body fat?',
		context:
      '⚖️ Visceral (belly) fat produces inflammatory cytokines that accelerate aging. Location matters more than total amount.',
		options: [
			{ value: 'visceral', label: 'Mostly belly/midsection', description: 'Apple shape, hard belly' },
			{ value: 'mixed', label: 'Both belly and hips/thighs', description: 'Distributed weight gain' },
			{ value: 'peripheral', label: 'Mostly hips/thighs', description: 'Pear shape, soft tissue' },
			{ value: 'lean', label: 'Very lean/athletic', description: 'Low body fat overall' },
		],
		required: true,
		category: 'Body',
	},
	{
		id: 'inflammation',
		kind: 'options',
		title: 'Question 8 - Inflammation',
		label: 'Do you experience joint pain, stiffness, or general aches?',
		context:
      '🔥 Chronic inflammation ("inflammaging") is a hallmark of biological aging. These symptoms often indicate elevated CRP and IL-6.',
		options: [
			{ value: 'daily', label: 'Daily pain/stiffness', description: 'Constant discomfort' },
			{ value: 'frequent', label: 'Frequent (most weeks)', description: 'Recurring issues' },
			{ value: 'occasional', label: 'Occasional (some months)', description: 'Intermittent symptoms' },
			{ value: 'none', label: 'Rarely or never', description: 'No notable issues' },
		],
		required: true,
		category: 'Inflammation',
	},
	{
		id: 'cognition',
		kind: 'options',
		title: 'Question 9 - Cognitive Function',
		label: 'How often do you experience brain fog or memory issues?',
		context:
      '🧠 Cognitive decline starts decades before symptoms. Brain fog often indicates mitochondrial dysfunction or inflammation.',
		options: [
			{ value: 'constant', label: 'Constant', description: 'Most days severely affected' },
			{ value: 'daily', label: 'Daily', description: 'Daily noticeable issues' },
			{ value: 'weekly', label: 'Weekly', description: 'Some weeks affected' },
			{ value: 'rare', label: 'Rarely/Never', description: 'No or rare symptoms' },
		],
		required: true,
		category: 'Cognition',
	},
	{
		id: 'hormones',
		kind: 'options',
		title: 'Question 10 - Hormonal Health',
		label: 'Which hormonal symptoms do you experience? (Select most prominent)',
		context: '⚗️ Hormone decline is a major aging accelerator. These symptoms indicate specific hormone imbalances.',
		options: [
			{ value: 'low-energy-libido', label: 'Low energy and/or low libido', description: 'Fatigue, reduced drive' },
			{ value: 'mood-sleep', label: 'Mood or sleep issues', description: 'Irritability, poor sleep quality' },
			{ value: 'weight-temp', label: 'Weight gain or cold intolerance', description: 'Metabolic and thyroid-related symptoms' },
			{ value: 'none', label: 'None of the above', description: 'No notable hormonal symptoms' },
		],
		required: false,
		category: 'Hormones',
	},
	{
		id: 'family-history',
		kind: 'options',
		title: 'Question 11 - Family History',
		label: 'What chronic conditions run in your immediate family?',
		context:
			'🧬 Genetics load the gun, lifestyle pulls the trigger. Family history helps prioritize which biomarkers to monitor.',
		options: [
			{ value: 'cardiovascular', label: 'Cardiovascular disease', description: 'Heart disease, hypertension' },
			{ value: 'metabolic', label: 'Metabolic issues (diabetes)', description: 'Type 2 diabetes, insulin resistance' },
			{ value: 'cancer', label: 'Cancer', description: 'Immediate family cancer history' },
			{ value: 'longevity', label: 'Exceptional longevity (90+)', description: 'Parents/grandparents lived past 90' },
		],
		required: false,
		category: 'History',
	},
	{
		id: 'digestive',
		kind: 'options',
		title: 'Question 12 - Digestive Health',
		label: 'How often do you experience digestive issues?',
		context:
			'🦠 Gut health affects everything from immunity to mood. Poor digestion often indicates dysbiosis and inflammation.',
		options: [
			{ value: 'daily', label: 'Daily', description: 'Frequent bloating, discomfort' },
			{ value: 'frequent', label: 'Frequent', description: 'Most weeks have symptoms' },
			{ value: 'occasional', label: 'Occasional', description: 'Some months affected' },
			{ value: 'excellent', label: 'Rarely/Never (excellent)', description: 'Healthy, regular digestion' },
		],
		required: false,
		category: 'Digestive',
	},
	{
		id: 'healing',
		kind: 'options',
		title: 'Question 13 - Recovery & Healing',
		label: 'How quickly do you heal from cuts, bruises, or workouts?',
		context: '🔄 Healing speed directly reflects biological age. Slow recovery indicates cellular dysfunction.',
		options: [
			{ value: 'very-slow', label: 'Very slow healing', description: 'Weeks for minor injuries' },
			{ value: 'slow', label: 'Slow healing', description: 'Takes several days' },
			{ value: 'normal', label: 'Normal healing', description: 'Typical recovery time' },
			{ value: 'fast', label: 'Fast healing', description: 'Bounce back quickly' },
		],
		required: false,
		category: 'Recovery',
	},
	{
		id: 'sun',
		kind: 'options',
		title: 'Question 14 - Sun Exposure',
		label: 'How much quality sun exposure do you get?',
		context: '☀️ Vitamin D is crucial for 3000+ genes. Most people are deficient, accelerating aging and disease risk.',
		options: [
			{ value: 'minimal', label: 'Minimal - mostly indoor', description: 'Rarely outdoors, limited sun' },
			{ value: 'moderate', label: 'Moderate', description: 'Some weekday exposure' },
			{ value: 'regular', label: 'Regular', description: 'Daily short outdoor exposure' },
			{ value: 'optimal', label: 'Optimal', description: '15–30 minutes midday, adequate vitamin D' },
		],
		required: false,
		category: 'Sun',
	},
	{
		id: 'water',
		kind: 'options',
		title: 'Question 15 - Toxin Exposure',
		label: 'What\'s your primary source of drinking water?',
		context: '💧 Water quality affects mineral status and toxin load. Heavy metals and chemicals accelerate aging.',
		options: [
			{ value: 'tap', label: 'Tap', description: 'Unfiltered municipal water' },
			{ value: 'basic-filter', label: 'Basic filter', description: 'Pitcher or simple carbon filter' },
			{ value: 'quality-filter', label: 'Quality filter (RO/distilled)', description: 'Reverse osmosis or distilled' },
			{ value: 'remineralized', label: 'Quality + remineralized', description: 'RO/distilled with minerals added back' },
		],
		required: false,
		category: 'Toxins',
	},
	{
		id: 'skin',
		kind: 'options',
		title: 'Question 16 - Skin Health',
		label: 'How has your skin changed in recent years?',
		context: '🧴 Skin is your largest organ and reflects internal health. Premature aging signs indicate systemic issues.',
		options: [
			{ value: 'rapid-aging', label: 'Rapid aging', description: 'Deep wrinkles, sagging, age spots increasing quickly' },
			{ value: 'moderate-aging', label: 'Moderate aging', description: 'Fine lines, mild elasticity loss, some discoloration' },
			{ value: 'slow-aging', label: 'Slow aging', description: 'Minimal changes, generally smooth skin' },
			{ value: 'youthful', label: 'Youthful', description: 'Clear, elastic, vibrant skin tone' },
		],
		required: false,
		category: 'Skin',
	},
	{
		id: 'labwork',
		kind: 'options',
		title: 'Question 17 - Medical History',
		label: 'When did you last have comprehensive blood work?',
		context: '🔬 Regular testing is the only way to catch problems early. Most people are walking around with undiagnosed issues.',
		options: [
			{ value: 'never', label: 'Never', description: 'No comprehensive panels' },
			{ value: 'years', label: 'Years ago', description: 'Multiple years since labs' },
			{ value: 'recent', label: 'Within the last year', description: 'Recent standard labs' },
			{ value: 'comprehensive', label: 'Recent and comprehensive', description: 'Full panel in last 12 months' },
		],
		required: false,
		category: 'Labs',
	},
	{
		id: 'supplementation',
		kind: 'options',
		title: 'Question 18 - Supplementation',
		label: 'How do you currently approach supplementation?',
		context: '💊 Random supplementation can be harmful. Personalized protocols based on testing are most effective.',
		options: [
			{ value: 'none', label: 'None', description: 'No supplements currently' },
			{ value: 'random', label: 'Random', description: 'Take various supplements inconsistently' },
			{ value: 'basic', label: 'Basic multivitamin', description: 'Simple multi, occasional extras' },
			{ value: 'targeted', label: 'Targeted, based on testing', description: 'Personalized regimen guided by data' },
		],
		required: false,
		category: 'Supplements',
	},
	{
		id: 'goal',
		kind: 'options',
		title: 'Question 19 - Goals',
		label: 'What\'s your #1 health optimization priority?',
		context: '🎯 Your goals determine which biomarkers matter most and what interventions to prioritize.',
		options: [
			{ value: 'energy', label: 'Energy', description: 'Beat fatigue, stabilize daily energy' },
			{ value: 'longevity', label: 'Longevity', description: 'Slow aging and extend healthspan' },
			{ value: 'performance', label: 'Performance', description: 'Improve strength, VO2, and recovery' },
			{ value: 'prevention', label: 'Prevention', description: 'Reduce disease risk proactively' },
		],
		required: false,
		category: 'Goals',
	},
	{
		id: 'email',
		kind: 'input',
		title: 'Final Step - Get Your Results',
		label: 'Enter your email to receive your complete longevity report:',
		placeholder: 'your@email.com',
		inputType: 'email',
		required: true,
		category: 'Contact',
	},
	{
		id: 'summary',
		kind: 'summary',
	},
];

export const countCoreQuestions = assessmentQuestions.filter(q => !['intro', 'summary'].includes(q.kind)).length;
